channels:
  - pytorch
  - conda-forge
dependencies:
  - scikit-learn
  - pyyaml
  - pytest
  - h5py
  - pytest
  - bokeh
  - pip
  - matplotlib
  - pip:
    - DeepForest
    - rasterstats
    - bumpversion
    - comet_ml
    - dask
    - distributed
    - dask_jobqueue
